[project]
name = "abm-platform-training"
channels = ["conda-forge"]
platforms = ["linux-aarch64", "linux-64"]

[dependencies]
python = "=3.12"
r-irkernel = ">=1.3.2,<2"

[pypi-dependencies]
abm = "~=2.0"
ipykernel = "~=6.29"
numpy = "~=1.26"
pandas = "~=2.2"
ipywidgets = "~=8.1"
pzfx_parser = "~=0.4"
openpyxl = "~=3.1"
matplotlib = "~=3.8"
plotly = "~=5.21"
plotnine = "~=0.13"
nbmake = "~=1.5"
pytest = "~=8.1"
